# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphingWidget(object):
    def setupUi(self, GraphingWidget):
        GraphingWidget.setObjectName("GraphingWidget")
        GraphingWidget.resize(1045, 645)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        GraphingWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(GraphingWidget)
        QtCore.QMetaObject.connectSlotsByName(GraphingWidget)

    def retranslateUi(self, GraphingWidget):
        _translate = QtCore.QCoreApplication.translate
        GraphingWidget.setWindowTitle(_translate("GraphingWidget", "DockWidget"))
