# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParametersWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParametersWidget(object):
    def setupUi(self, ParametersWidget):
        ParametersWidget.setObjectName("ParametersWidget")
        ParametersWidget.resize(577, 574)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(40, 40, 411, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        ParametersWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(ParametersWidget)
        QtCore.QMetaObject.connectSlotsByName(ParametersWidget)

    def retranslateUi(self, ParametersWidget):
        _translate = QtCore.QCoreApplication.translate
        ParametersWidget.setWindowTitle(_translate("ParametersWidget", "DockWidget"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ParametersWidget", "Roll"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ParametersWidget", "Yaw"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ParametersWidget", "Pitch"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("ParametersWidget", "Throttle"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ParametersWidget", "Value"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ParametersWidget", "Parameters"))
