# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PayloadWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PayloadWidget(object):
    def setupUi(self, PayloadWidget):
        PayloadWidget.setObjectName("PayloadWidget")
        PayloadWidget.resize(912, 596)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(40, 50, 801, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        PayloadWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(PayloadWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PayloadWidget)

    def retranslateUi(self, PayloadWidget):
        _translate = QtCore.QCoreApplication.translate
        PayloadWidget.setWindowTitle(_translate("PayloadWidget", "DockWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PayloadWidget", "Payload 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PayloadWidget", "Payload 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PayloadWidget", "Payload 3"))
